name: sync_fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: emacs-mirror
          base: master
          head: master
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: emacs-mirror
          base: ff
          head: master
